# Generated by Django 5.2.9 on 2026-01-04 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_booking_system', '0002_alter_timeslot_from_time_alter_timeslot_to_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting_booking_system.timeslot'),
        ),
    ]
