# Generated by Django 5.2.9 on 2026-01-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_booking_system', '0003_alter_booking_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
